twitter_credentials: 

  ACCES_KEY: 95U6x3ih1MIzIMlGZxuIuXN8t
  ACCES_SECRET: UvO4jKztNuN0SdtQtcD5z69iBqsGXAjvMyRLn9IXcSfB6mPLVg
  CONSUMER_KEY: 1572886741-LOU6Eq8XuH1piFGql1V0yBxRfNaCQ4RpyZJUSu5
  CONSUMER_SECRET: CSVMuSHqkydo21OzDHaT8RQaMljR8Q4tNdP9X3gHlUt2p

api_finance_config: 

  url_symbols: https://api.binance.com/api/v3/ticker/price
  timeout: 5
  url_data: https://api.kucoin.com/api/v1/market/stats?symbol=

kafka_config:
  
  topic_data: finance
  topic_tweets: tweets
  bootstrap_servers: localhost:9092
 
spark_config: 

  master: yarn
  app_name: Finance_tweet_dashboard
  checkpoint_path: gs://financed-data/cheks
  data_path: gs://financed-data/data
  batch_duration: 10 seconds
  outputMode: append
  topic_data: finance
  topic_tweets: tweets
  bootstrap_servers: 10.200.0.2:9092

monog_db: 
  
  db_connection: mongodb+srv://ghiles:ghiles10@cluster0.ru8hmhi.mongodb.net/?retryWrites=true&w=majority
  bucket_name: financed-data

  
elastic_search: 

  cloud_id: 4b14cabeeeff4e59a05853191d8aa21b:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDM4Y2MxMWU1NTIzZjQ4YzE4MTY0NWVjMGQzYTU3NzZhJDk4NzM3MTkyZDJmMDQ4MjY4ZDNlMGJkZTY1NmY2NDNk
  user : ghiles 
  password : ghiles10 
  index_name : tweets
  
big_query: 

  project_id: data-engineering-streaming
  dataset_id: finance
  bucket_name: financed-data
  google_application_credentials: "/opt/airflow/plugins/google_credentials.json"
  table_id: temp_table
